<?php

use Illuminate\Database\Seeder;

class CollectionTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datetime = date('Y-m-d H:i:s');
        DB::table('collection_types')->insert([
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-01',
                'name' => 'Zakat Fitrah',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-02',
                'name' => 'Zakat Wang Simpanan',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-03',
                'name' => 'Zakat Pendapatan (KAUNTER)',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-04',
                'name' => 'Zakat Pendapatan (ZPG)',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-05',
                'name' => 'Zakat Perniagaan',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-06',
                'name' => 'Zakat Saham',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-07',
                'name' => 'Zakat KWSP',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-08',
                'name' => 'Zakat Emas dan Perak',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-09',
                'name' => 'Zakat Ternakan',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-10',
                'name' => 'Zakat Tanaman',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-11',
                'name' => 'Fidyah',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-12',
                'name' => 'Kafarah',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-13',
                'name' => 'Nazar',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-14',
                'name' => 'Lain-lain Hasil Zakat - Hasil Pelaburan Tunai',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 1,
                'fund' => 'Dana Zakat',
                'code' => 'IN01-15',
                'name' => 'Lain-lain Hasil Zakat - Hasil Dividen Saham',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-01',
                'name' => 'Sumbangan Wajib',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-02',
                'name' => 'Derma',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-03',
                'name' => 'Sewa Bangunan / Rumah Kedai',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-04',
                'name' => 'Hasil Pelaburan Tunai',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-05',
                'name' => 'Hasil Dividen Saham',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-06',
                'name' => 'Lain-lain Hasil Baitulmal - Insuran',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-07',
                'name' => 'Lain-lain Hasil Baitulmal - Kelas Agama Dewasa',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-08',
                'name' => 'Lain-lain Hasil Baitulmal - Ruang Letak Kereta',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-09',
                'name' => 'Lain-lain Hasil Baitulmal - Jualan Buku',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-10',
                'name' => 'Lain-lain Hasil Baitulmal - Hasil Akaun Semasa',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-11',
                'name' => 'Lain-lain Hasil Baitulmal - Yuran Taski BPP',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-12',
                'name' => "Lain-lain Hasil Baitulmal - Ta'liq Talak",
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-13',
                'name' => 'Lain-lain Hasil Baitulmal - Caj Kursus Pra Perkahwinan',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 2,
                'fund' => 'Dana Baitulmal',
                'code' => 'IN02-14',
                'name' => 'Lain-lain Hasil Baitulmal - Pelbagai',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 3,
                'fund' => 'Dana Wakaf',
                'code' => 'IN03-01',
                'name' => 'Wakaf Khas Tunai',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 3,
                'fund' => 'Dana Wakaf',
                'code' => 'IN03-02',
                'name' => 'Wakaf Am Tunai',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 3,
                'fund' => 'Dana Wakaf',
                'code' => 'IN03-03',
                'name' => 'Wakaf Potong Gaji',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 3,
                'fund' => 'Dana Wakaf',
                'code' => 'IN03-04',
                'name' => 'Lain-lain Hasil Wakaf - Hasil Pelaburan Tunai',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 3,
                'fund' => 'Dana Wakaf',
                'code' => 'IN03-05',
                'name' => 'Lain-lain Hasil Wakaf - Hasil Sewa Medan Hamidah (MH)',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 3,
                'fund' => 'Dana Wakaf',
                'code' => 'IN03-06',
                'name' => 'Lain-lain Hasil Wakaf - Hasil Sewa Fasiliti Pusat Penerangan Islam (IIC)',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 3,
                'fund' => 'Dana Wakaf',
                'code' => 'IN03-07',
                'name' => 'Lain-lain Hasil Wakaf - Hasil Sewa Rumah Wakaf',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],
            [
                'fund_id' => 3,
                'fund' => 'Dana Wakaf',
                'code' => 'IN03-08',
                'name' => 'Lain-lain Hasil Wakaf - Hasil Sewa Tanah Wakaf',
                'created_at' => $datetime,
                'updated_at' => $datetime,
            ],       
        ]);
    }
}
